### ISSUE TITLE
This is cool

### ISSUE THREAD

**Issue by penfold42** [simap/pixelblaze#1]
And I'd love to help incorporate  it with 
Espixelstick https://github.com/forkineye/ESPixelStick

And Hyperion
https://github.com/hyperion-project/hyperion.ng

Is the source available ? I can only find docs and images.

**Comment by simap** [comment]
Thanks!
Currently the software not open source. It's something I've considered, but I'm trying to balance selling the boards commercially to pay for my time, and contributing to the community. I've open sourced a few bits of it here and there, and will continue to do that as I have time to libraryify and document. 

What kind of integration do you have in mind? 
Pixelblaze has a websocket API that can control variables used in expressions.

**Comment by penfold42** [comment]
Both projects have support for an effects engine and I thought this could 
 add another approach.

**Comment by simap** [comment]
@penfold42 before I wrote a whole new engine for Pixelblaze, I experimented with https://github.com/jamesgregson/expression_parser
The benefit with above is that you don't need to do too much trickery to get live code reload, as it just parses the expression string each time.

**Comment by penfold42** [comment]
Thanks for the pointer !
