### ISSUE TITLE
Link to precompiled firmware

### ISSUE THREAD

**Issue by NZSmartie** [simap/pixelblaze#3]
Although the source code isn't available yet. Would you be willing to release the firmware as a binary blob so that others may flash it to their own ESP8266 to give it a try?

**Comment by simap** [comment]
If you are interested in licensing the firmware for your own hardware or product, please DM me. If you'd like to see it in action, I have a few videos where I demo the interface. 

https://www.youtube.com/watch?v=3ugNIZ96UK4
https://www.youtube.com/watch?v=vDD5uiRcSCk
