### ISSUE TITLE
2811 Trace?

### ISSUE THREAD

**Issue by dansteingart** [simap/pixelblaze#4]
I have a string of WS2801's (bought from adafruit a few year ago) that aren't working. Do have to do something to this 2811 trace on the bottom of the board?

**Comment by simap** [comment]
Nope, you can cut it if you don't need ws2811/2812 support and get an extra gpio.
Ws2801 should work either way.

You'll need to select that led type in settings, and set the number of pixels, you can try lowering the speed to see if that helps. Also double check clock and data. If you're using screw terminals, also double check that the wire is stripped enough to make contact with the metal and for cold solder joints.

If you have another way to test the ws2801, that might be worth a try. 

I test all Pixelblazes before shipping, but if it's not working I'll get you a replacement.

**Comment by simap** [comment]
Let me know if it's still not working for you
